/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.RecordGame;

import Entities.PlayerDetails;
import Entities.User;
import Entities.UserGameDetails;
import Utils.AppManager;
import Utils.ConnectionManager;
import Utils.UserGameDetailsCrud;
import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.awt.Label;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;

/**
 *
 * @author A H M E D
 */
public class RecordedGames extends javax.swing.JFrame {

    
    AppManager appManager;
    UserGameDetailsCrud userGameDetailsCrud;
    ConnectionManager cm;
    public RecordedGames() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            appManager = AppManager.getInstance();
            cm = ConnectionManager.getInstance();
            userGameDetailsCrud= new UserGameDetailsCrud(cm.in,cm.out);

        } catch (IOException ex) {
            Logger.getLogger(RecordedGames.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void replay(UserGameDetails userGameDetails){
        Replay r = new Replay(userGameDetails);
        r.setVisible(true);
        r.start();
    }
    
    public void init() throws IOException{
        recordsList.removeAll();
        new Thread(()->{
        
            try {
                ArrayList<UserGameDetails> userGamesDetails = userGameDetailsCrud.getAllWithId(appManager.getUser().getId());
                
                for (Iterator<UserGameDetails> iterator = userGamesDetails.iterator(); iterator.hasNext();) {
                    UserGameDetails next = iterator.next();
                    PlayerDetails p = next.getPlayerWithId(appManager.getUser().getId());
                    if(!p.getIsRecorded())
                        continue;
                    
                    RecordedRow rr = new RecordedRow(p.getPlayerState(),next.playerOneDetails,next.playerTwoDetails);
                    rr.addMouseListener(new MouseAdapter(){
                        @Override
                        public void mouseClicked(MouseEvent e) {
                            super.mouseClicked(e);
                            replay(next);
                        }
                    });
                    EventQueue.invokeLater(()->{
                        recordsList.add(rr);
                        revalidate();
                    });
                }   
            } catch (IOException ex) {
                Logger.getLogger(RecordedGames.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }).start();
        
        
    }
    
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        recordsList = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 386));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setMaximumSize(new java.awt.Dimension(902, 424));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(902, 424));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(902, 424));

        recordsList.setBackground(new java.awt.Color(0, 0, 0));
        recordsList.setMaximumSize(new java.awt.Dimension(902, 424));
        recordsList.setMinimumSize(new java.awt.Dimension(902, 424));
        recordsList.setPreferredSize(new java.awt.Dimension(900, 410));
        jScrollPane2.setViewportView(recordsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordedGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordedGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordedGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordedGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordedGames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel recordsList;
    // End of variables declaration//GEN-END:variables
}
