/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Entities.PlayerDetails;
import Entities.User;
import Entities.UserGameDetails;
import Entities.UserGameDetails.PlayerState;
import Utils.AppManager;
import Utils.ConnectionManager;
import Utils.UserGameDetailsCrud;
import java.awt.Color;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Tarek
 */
public class MultiLocal extends javax.swing.JFrame {

   
    int x_pressed = 0;
    int y_pressed = 0;
    int e;
    String XSimbole = "/UI/Board/xCol2.png";
    String OSimbole = "/UI/Board/oCol2.png";
    String XWin = "/UI/Board/xWin.png";
    String OWin = "/UI/Board/oWin.png";

    String XPng ="/UI/Board/Xpngg.png";
    String oPng="/UI/Board/opng.png";
    String background="/UI/Board/background.png";
    boolean player1_turn;
    JButton[] buttons = new JButton[9];
    UserGameDetails userGameDetails;
    
    AppManager appManager;
    ConnectionManager cm;
    
    

    /**
     * Creates new form NewJFrame
     */
    public MultiLocal() {
        initComponents();
        try {
            cm = ConnectionManager.getInstance();
        } catch (IOException ex) {
            Logger.getLogger(MultiLocal.class.getName()).log(Level.SEVERE, null, ex);
        }
        appManager = AppManager.getinstance();
        userGameDetails = new UserGameDetails(
            UserGameDetails.GameModes.Single,
            UserGameDetails.GameDifficultyLvl.Intermediate,
            new PlayerDetails(
                appManager.getUser(),
                UserGameDetails.PlayerSimbole.X,
                true
            ),
            new PlayerDetails(
                new User(Home.player2),
                UserGameDetails.PlayerSimbole.O,
                false
            )
        );
       
        jLabel10.setText(Home.player2);
        jLabel9.setText(Home.player1);

        setLocationRelativeTo(null);
        buttons[0] = btn0;
        buttons[1] = btn1;
        buttons[2] = btn2;
        buttons[3] = btn3;
        buttons[4] = btn4;
        buttons[5] = btn5;
        buttons[6] = btn6;
        buttons[7] = btn7;
        buttons[8] = btn8;
        for (int i = 0; i <9; i++) {
            buttons[i].setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dragLabel = new javax.swing.JLabel();
        frstTurn = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/background.png"))); // NOI18N
        btn0.setBorder(null);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 110, 90));

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/background.png"))); // NOI18N
        btn1.setBorder(null);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 146, 110, 93));

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/background.png"))); // NOI18N
        btn2.setBorder(null);
        btn2.setBorderPainted(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 146, 105, 93));

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/background.png"))); // NOI18N
        btn6.setBorder(null);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 355, 108, 93));

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/background.png"))); // NOI18N
        btn7.setBorder(null);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 355, 110, 93));

        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/background.png"))); // NOI18N
        btn8.setBorder(null);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 355, 105, 93));

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/background.png"))); // NOI18N
        btn3.setBorder(null);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 108, 93));

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/background.png"))); // NOI18N
        btn4.setBorder(null);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 250, 110, 93));

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/background.png"))); // NOI18N
        btn5.setBorder(null);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 250, 105, 93));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("x");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -10, -1, -1));

        dragLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragLabelMouseDragged(evt);
            }
        });
        dragLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragLabelMousePressed(evt);
            }
        });
        jPanel1.add(dragLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        frstTurn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        frstTurn.setForeground(new java.awt.Color(255, 255, 0));
        frstTurn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(frstTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 360, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/oPng.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 320, 60, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/XPngg.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 320, 60, 60));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("NickNaame");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 270, 140, 30));

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("NickNaame");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 150, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Player 2");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 240, 80, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Player 1");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 80, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/playerB.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 150, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/playerB.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 150, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/test7.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 130, 380, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Board/background.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
       
     
        if(player1_turn){
            if(btn0.getText()=="") {
                player1_turn=false;
                btn0.setText("x");
                frstTurn.setText("O turn");
                btn0.setIcon(new ImageIcon(getClass().getResource(XSimbole)));
                userGameDetails.gameBord.put(1, UserGameDetails.PlayerSimbole.X);
                check() ;
            }
        }else{
            if(btn0.getText()==""){
                player1_turn=true;
                btn0.setText("o");
                frstTurn.setText("X turn");
                btn0.setIcon(new ImageIcon(getClass().getResource(OSimbole)));
                userGameDetails.gameBord.put(1, UserGameDetails.PlayerSimbole.O);
                check();
            }
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if(player1_turn){
            if(btn1.getText()=="") {
                player1_turn=false;
                btn1.setText("x");
                frstTurn.setText("O turn");
                btn1.setIcon(new ImageIcon(getClass().getResource(XSimbole)));
                userGameDetails.gameBord.put(2, UserGameDetails.PlayerSimbole.X);
                check() ;
            }
        }else{
            if(btn1.getText()==""){
                player1_turn=true;
                btn1.setText("o");
                frstTurn.setText("X turn");
                btn1.setIcon(new ImageIcon(getClass().getResource(OSimbole)));
                userGameDetails.gameBord.put(2, UserGameDetails.PlayerSimbole.O);
                check();
            }
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if(player1_turn){
            if(btn2.getText()=="") {
                player1_turn=false;
                btn2.setText("x");
                frstTurn.setText("O turn");
                btn2.setIcon(new ImageIcon(getClass().getResource(XSimbole)));
                userGameDetails.gameBord.put(3, UserGameDetails.PlayerSimbole.X);
                check() ;
            }
        }else{
            if(btn2.getText()==""){
                player1_turn=true;
                btn2.setText("o");
                frstTurn.setText("X turn");
                btn2.setIcon(new ImageIcon(getClass().getResource(OSimbole)));
                userGameDetails.gameBord.put(3, UserGameDetails.PlayerSimbole.O);
                check();
            }
        }    
                                        
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
       if(player1_turn){
            if(btn6.getText()=="") {
                player1_turn=false;
                btn6.setText("x");
                frstTurn.setText("O turn");
                btn6.setIcon(new ImageIcon(getClass().getResource(XSimbole)));
                
                userGameDetails.gameBord.put(7, UserGameDetails.PlayerSimbole.X);
                check() ;
            }
        }else{
            if(btn6.getText()==""){
                player1_turn=true;
                btn6.setText("o");
                frstTurn.setText("X turn");
                btn6.setIcon(new ImageIcon(getClass().getResource(OSimbole)));
                userGameDetails.gameBord.put(7, UserGameDetails.PlayerSimbole.O);
                check();
            }
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if(player1_turn){
            if(btn7.getText()=="") {
                player1_turn=false;
                btn7.setText("x");
                frstTurn.setText("O turn");
                btn7.setIcon(new ImageIcon(getClass().getResource(XSimbole)));
                
                userGameDetails.gameBord.put(8, UserGameDetails.PlayerSimbole.X);
                check() ;
            }
        }else{
            if(btn7.getText()==""){
                player1_turn=true;
                btn7.setText("o");
                frstTurn.setText("X turn");
                btn7.setIcon(new ImageIcon(getClass().getResource(OSimbole)));
                userGameDetails.gameBord.put(8, UserGameDetails.PlayerSimbole.O);
                check();
            }
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if(player1_turn){
            if(btn8.getText()=="") {
                player1_turn=false;
                btn8.setText("x");
                frstTurn.setText("O turn");
                btn8.setIcon(new ImageIcon(getClass().getResource(XSimbole)));
                
                userGameDetails.gameBord.put(9, UserGameDetails.PlayerSimbole.X);
                check() ;
            }
        }else{
            if(btn8.getText()==""){
                player1_turn=true;
                btn8.setText("o");
                frstTurn.setText("X turn");
                btn8.setIcon(new ImageIcon(getClass().getResource(OSimbole)));
                userGameDetails.gameBord.put(9, UserGameDetails.PlayerSimbole.O);
                check();
            }
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if(player1_turn){
            if(btn3.getText()=="") {
                player1_turn=false;
                btn3.setText("x");
                frstTurn.setText("O turn");
                btn3.setIcon(new ImageIcon(getClass().getResource(XSimbole)));
                
                userGameDetails.gameBord.put(4, UserGameDetails.PlayerSimbole.X);
                check() ;
            }
        }else{
            if(btn3.getText()==""){
                player1_turn=true;
                btn3.setText("o");
                frstTurn.setText("X turn");
                btn3.setIcon(new ImageIcon(getClass().getResource(OSimbole)));
                userGameDetails.gameBord.put(4, UserGameDetails.PlayerSimbole.O);
                check();
            }
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if(player1_turn){
            if(btn4.getText()=="") {
                player1_turn=false;
                btn4.setText("x");
                frstTurn.setText("O turn");
                btn4.setIcon(new ImageIcon(getClass().getResource(XSimbole)));
                
                userGameDetails.gameBord.put(5, UserGameDetails.PlayerSimbole.X);
                check() ;
            }
        }else{
            if(btn4.getText()==""){
                player1_turn=true;
                btn4.setText("o");
                frstTurn.setText("X turn");
                btn4.setIcon(new ImageIcon(getClass().getResource(OSimbole)));
                userGameDetails.gameBord.put(5, UserGameDetails.PlayerSimbole.O);
                check();
            }
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
  if(player1_turn){
            if(btn5.getText()=="") {
                player1_turn=false;
                btn5.setText("x");
                frstTurn.setText("O turn");
                btn5.setIcon(new ImageIcon(getClass().getResource(XSimbole)));
                
                userGameDetails.gameBord.put(6, UserGameDetails.PlayerSimbole.X);
                check() ;
            }
        }else{
            if(btn5.getText()==""){
                player1_turn=true;
                btn5.setText("o");
                frstTurn.setText("X turn");
                btn5.setIcon(new ImageIcon(getClass().getResource(OSimbole)));
                userGameDetails.gameBord.put(6, UserGameDetails.PlayerSimbole.O);
                check();
            }
        }
            }//GEN-LAST:event_btn5ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void dragLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragLabelMouseDragged
        setLocation(evt.getXOnScreen() - x_pressed, evt.getYOnScreen() - y_pressed);
    }//GEN-LAST:event_dragLabelMouseDragged

    private void dragLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragLabelMousePressed
        x_pressed = evt.getX();
        y_pressed = evt.getY();
    }//GEN-LAST:event_dragLabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiLocal().setVisible(true);
            }
        });
    }
     public void playAgain(){
        recordGame();
        int n = JOptionPane.showConfirmDialog(
        this,
        "Do you want to play again?",
        "Click a button",
        JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){
            for (int i = 0; i < 9; i++) {
                buttons[i].setText("");
                buttons[i].setIcon(new ImageIcon(getClass().getResource(background)));
            }
            frstTurn.setText("");
        }else{                 
            System.exit(0);
        }
    }
     
     
   public void check() {
       
      e=0;
               
                         
                    if((buttons[0].getText()!="") &&
                        (buttons[1].getText()!="") &&
                        (buttons[2].getText()!="")&&
                        (buttons[3].getText()!="") &&
                        (buttons[4].getText()!="") &&
                        (buttons[5].getText()!="")&&
                        (buttons[6].getText()!="") &&
                        (buttons[7].getText()!="") &&
                        (buttons[8].getText()!=""))
                       {
                e=1;};
		 
                         
		//check X win conditions
		if(
				(buttons[0].getText()=="x") &&
				(buttons[1].getText()=="x") &&
				(buttons[2].getText()=="x")
				) {
			xWins(0,1,2);
		}
		if(
				(buttons[3].getText()=="x") &&
				(buttons[4].getText()=="x") &&
				(buttons[5].getText()=="x")
				) {
			xWins(3,4,5);
		}
		if(
				(buttons[6].getText()=="x") &&
				(buttons[7].getText()=="x") &&
				(buttons[8].getText()=="x")
				) {
			xWins(6,7,8);
		}
		if(
				(buttons[0].getText()=="x") &&
				(buttons[3].getText()=="x") &&
				(buttons[6].getText()=="x")
				) {
			xWins(0,3,6);
		}
		if(
				(buttons[1].getText()=="x") &&
				(buttons[4].getText()=="x") &&
				(buttons[7].getText()=="x")
				) {
			xWins(1,4,7);
		}
		if(
				(buttons[2].getText()=="x") &&
				(buttons[5].getText()=="x") &&
				(buttons[8].getText()=="x")
				) {
			xWins(2,5,8);
		}
		if(
				(buttons[0].getText()=="x") &&
				(buttons[4].getText()=="x") &&
				(buttons[8].getText()=="x")
				) {
			xWins(0,4,8);
		}
		if(
				(buttons[2].getText()=="x") &&
				(buttons[4].getText()=="x") &&
				(buttons[6].getText()=="x")
				) {
			xWins(2,4,6);
		}
                
                
                
		//check O win conditions
		if(
				(buttons[0].getText()=="o") &&
				(buttons[1].getText()=="o") &&
				(buttons[2].getText()=="o")
				) {
			oWins(0,1,2);
		}
		if(
				(buttons[3].getText()=="o") &&
				(buttons[4].getText()=="o") &&
				(buttons[5].getText()=="o")
				) {
			oWins(3,4,5);
		}
		if(
				(buttons[6].getText()=="o") &&
				(buttons[7].getText()=="o") &&
				(buttons[8].getText()=="o")
				) {
			oWins(6,7,8);
		}
		if(
				(buttons[0].getText()=="o") &&
				(buttons[3].getText()=="o") &&
				(buttons[6].getText()=="o")
				) {
			oWins(0,3,6);
		}
		if(
				(buttons[1].getText()=="o") &&
				(buttons[4].getText()=="o") &&
				(buttons[7].getText()=="o")
				) {
			oWins(1,4,7);
		}
		if(
				(buttons[2].getText()=="o") &&
				(buttons[5].getText()=="o") &&
				(buttons[8].getText()=="o")
				) {
			oWins(2,5,8);
		}
		if(
				(buttons[0].getText()=="o") &&
				(buttons[4].getText()=="o") &&
				(buttons[8].getText()=="o")
				) {
			oWins(0,4,8);
		}
		if(
				(buttons[2].getText()=="o") &&
				(buttons[4].getText()=="o") &&
				(buttons[6].getText()=="o")
				) {
			oWins(2,4,6);
		}
                
                if(e==1){
                    playAgain();
                }
                
	}
   
	public void xWins(int a,int b,int c) {
           
		buttons[a].setIcon(new ImageIcon(getClass().getResource(XWin)));
		buttons[b].setIcon(new ImageIcon(getClass().getResource(XWin)));
		buttons[c].setIcon(new ImageIcon(getClass().getResource(XWin)));
                frstTurn.setText("X wins");
                
                userGameDetails.playerOneDetails.setPlayerState(PlayerState.Winner);
                userGameDetails.playerTwoDetails.setPlayerState(PlayerState.Loser);
                
		if(e!=1)
                    playAgain();
		 
	}
	public void oWins(int a,int b,int c) {
            //chang icon
		buttons[a].setIcon(new ImageIcon(getClass().getResource(OWin)));
		buttons[b].setIcon(new ImageIcon(getClass().getResource(OWin)));
		buttons[c].setIcon(new ImageIcon(getClass().getResource(OWin)));
                frstTurn.setText("O wins");
                
                userGameDetails.playerOneDetails.setPlayerState(PlayerState.Loser);
                userGameDetails.playerTwoDetails.setPlayerState(PlayerState.Winner);

                if(e!=1)
                    playAgain();
		
	}
        
        
        public void recordGame(){
            int n = JOptionPane.showConfirmDialog(
            this,
            "Do you want to Record this Game?",
            "Recording",
            JOptionPane.YES_NO_OPTION);
            if(n==JOptionPane.NO_OPTION)
                return;
            try {
                userGameDetails.playerOneDetails.setIsRecorded(true);
                new UserGameDetailsCrud(cm.in, cm.out).add(userGameDetails);
            } catch (IOException ex) {
                Logger.getLogger(MultiLocal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JLabel dragLabel;
    private javax.swing.JLabel frstTurn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
