/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import UI.Authentication.Login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hossa
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        loadingLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loadingValue = new javax.swing.JLabel();
        BackGroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackGroundPanel.setBackground(new java.awt.Color(0, 0, 153));
        BackGroundPanel.setPreferredSize(new java.awt.Dimension(900, 600));
        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/output-onlinepngtools (7).png"))); // NOI18N
        BackGroundPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 300, 310));
        BackGroundPanel.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 580, 930, 30));

        loadingLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        loadingLabel.setText("Loading...");
        BackGroundPanel.add(loadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("XO Game, ITI");
        BackGroundPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 390, -1, -1));

        loadingValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadingValue.setForeground(new java.awt.Color(255, 255, 255));
        loadingValue.setText("0 %");
        BackGroundPanel.add(loadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 50, -1));

        BackGroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/gredient.png"))); // NOI18N
        BackGroundImage.setText("jLabel1");
        BackGroundPanel.add(BackGroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
         SplashScreen sp = new SplashScreen();
        sp.setVisible(true);
        JFrame form = new Home();
        try{
            for(int i = 0 ; i<= 100 ; i++){
                Thread.sleep(40);
                sp.loadingValue.setText(i+"%");
                
                if(i == 10){
                    sp.loadingLabel.setText("Connecting...");
                }
                if(i == 20){
                    sp.loadingLabel.setText("Getting your data ready...");
                }
                if(i == 50){
                    sp.loadingLabel.setText("Loading your data...");
                }
                if(i == 70){
                    sp.loadingLabel.setText("Almost done...");
                }
                if(i == 90){
                    sp.loadingLabel.setText("Ready to play!");
                }
                if(i == 100){
                    
                    //JFrame log = new Login();
                    form.setLocationRelativeTo(null);
                    form.setVisible(true);
                    form.pack();
                    sp.dispose();
                }
                sp.jProgressBar1.setValue(i);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel BackGroundImage;
    protected javax.swing.JPanel BackGroundPanel;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel3;
    public javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JLabel loadingLabel;
    public javax.swing.JLabel loadingValue;
    // End of variables declaration//GEN-END:variables
}
